---
apiVersion: v1
kind: Pod
metadata:
  name: jenkins-master
spec:
  containers:
    - name: jenkins-master
      image: jenkins/jenkins:lts-jdk11
      volumeMounts:
        - mountPath: "/opt/jenkins"
          name: jenkins-master-data
  volumes:
    - name: jenkins-master-data
      persistentVolumeClaim:
        claimName: jenkins-pvc
